### ISSUE TITLE
Spaces vs Tabs

### ISSUE THREAD

**Issue by xboi209** [jjf28/Chkdraft#92]
Why are you using spaces now? Tabs makes the code look more clean and organized in my opinion.

**Comment by jjf28** [comment]
I'm not sure how its cleanliness/organization is adversely affected by this change, could you elaborate on that?

I decided to switch to spaces mainly because of the inconsistency between different programs/websites/browsers/users. Through some of these lenses tabs come out as long as 8 spaces (rather than the standard 4, in VS), requiring more scrolling or resulting in more code flowing onto subsequent lines (much less readable), can be especially painful on phones/small resolution devices.

Tabs also caused problems with 'pretty spaced' code (where params/array initializers are lined up nicely for easy reading) which could easily end up ugly. Admittedly the biggest issue here was that tabs were used for more than just the start-of-line to start-of-code portions; but making this change certainly helped identify/eliminate those that were in the middle and makes it very easy to do so in the future. It's also easier to find stray tabs than stray spaces, if keeping the project on a 100% consistent convention ever became relevant (using different forms I’ve heard, can cause lotsa merge issues).

Productivity wise I find the two indentation options to be quite equivalent, Visual Studios can easily be set to turn tab key-presses into 4-spaces (Tools->Options->Text Editor->C/C++->Tabs); white space can be easily jumped with ctrl+arrows or deleted with ctrl+delete and inserting or re-inserting a ; or } automatically spaces chunks of code.

For tabs the only advantages I read up on and considered legitimate was the ability for users to set their size (in some programs, not all give this option) and the relative ease for newer coders - which didn't, in my opinion, outweigh their disadvantages.

Some discussion on the matter:
	http://programmers.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e

It appears I can't link SEN shoutbox convos, so http://www.staredit.net/shoutboxsearch/ + starter phrase "like my friend and I decide for our project that indentation is to be this many spaces" then hit context.
